force-file-write: true
formatter: goimports
generate: true
log-level: info
template: testify
packages:
  manage-product-service/internal/repository:
    config:
      dir: internal/repository/mocks
      filename: ProductRepository.go
      pkgname: mocks
      structname: ProductRepository
    interfaces:
      ProductRepository: {}
  manage-product-service/internal/service:
    config:
      dir: internal/service/mocks
      filename: ProductService.go
      pkgname: mocks
      structname: ProductService
    interfaces:
      ProductService: {}
