name: manage-product-service
services:
  app:
    container_name: manage-product-service-app
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    volumes:
      - .:/app
    command: air -c .air.toml
  postgres:
    container_name: manage-product-service-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: always
    