// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"manage-product-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewProductRepository creates a new instance of ProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepository {
	mock := &ProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductRepository is an autogenerated mock type for the ProductRepository type
type ProductRepository struct {
	mock.Mock
}

type ProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductRepository) EXPECT() *ProductRepository_Expecter {
	return &ProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Create(product *model.Product) (int64, error) {
	ret := _mock.Called(product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.Product) (int64, error)); ok {
		return returnFunc(product)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.Product) int64); ok {
		r0 = returnFunc(product)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*model.Product) error); ok {
		r1 = returnFunc(product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - product *model.Product
func (_e *ProductRepository_Expecter) Create(product interface{}) *ProductRepository_Create_Call {
	return &ProductRepository_Create_Call{Call: _e.mock.On("Create", product)}
}

func (_c *ProductRepository_Create_Call) Run(run func(product *model.Product)) *ProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Product
		if args[0] != nil {
			arg0 = args[0].(*model.Product)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProductRepository_Create_Call) Return(n int64, err error) *ProductRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ProductRepository_Create_Call) RunAndReturn(run func(product *model.Product) (int64, error)) *ProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProductRepository
func (_mock *ProductRepository) Update(n int64, stringToIfaceVal map[string]interface{}) error {
	ret := _mock.Called(n, stringToIfaceVal)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, map[string]interface{}) error); ok {
		r0 = returnFunc(n, stringToIfaceVal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - n int64
//   - stringToIfaceVal map[string]interface{}
func (_e *ProductRepository_Expecter) Update(n interface{}, stringToIfaceVal interface{}) *ProductRepository_Update_Call {
	return &ProductRepository_Update_Call{Call: _e.mock.On("Update", n, stringToIfaceVal)}
}

func (_c *ProductRepository_Update_Call) Run(run func(n int64, stringToIfaceVal map[string]interface{})) *ProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductRepository_Update_Call) Return(err error) *ProductRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductRepository_Update_Call) RunAndReturn(run func(n int64, stringToIfaceVal map[string]interface{}) error) *ProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
