// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"manage-product-service/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

type ProductService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductService) EXPECT() *ProductService_Expecter {
	return &ProductService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ProductService
func (_mock *ProductService) Create(productRequest *model.ProductRequest) (int64, error) {
	ret := _mock.Called(productRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.ProductRequest) (int64, error)); ok {
		return returnFunc(productRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.ProductRequest) int64); ok {
		r0 = returnFunc(productRequest)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(*model.ProductRequest) error); ok {
		r1 = returnFunc(productRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProductService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ProductService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - productRequest *model.ProductRequest
func (_e *ProductService_Expecter) Create(productRequest interface{}) *ProductService_Create_Call {
	return &ProductService_Create_Call{Call: _e.mock.On("Create", productRequest)}
}

func (_c *ProductService_Create_Call) Run(run func(productRequest *model.ProductRequest)) *ProductService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.ProductRequest
		if args[0] != nil {
			arg0 = args[0].(*model.ProductRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProductService_Create_Call) Return(n int64, err error) *ProductService_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ProductService_Create_Call) RunAndReturn(run func(productRequest *model.ProductRequest) (int64, error)) *ProductService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ProductService
func (_mock *ProductService) Update(n int64, stringToIfaceVal map[string]interface{}) error {
	ret := _mock.Called(n, stringToIfaceVal)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int64, map[string]interface{}) error); ok {
		r0 = returnFunc(n, stringToIfaceVal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProductService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProductService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - n int64
//   - stringToIfaceVal map[string]interface{}
func (_e *ProductService_Expecter) Update(n interface{}, stringToIfaceVal interface{}) *ProductService_Update_Call {
	return &ProductService_Update_Call{Call: _e.mock.On("Update", n, stringToIfaceVal)}
}

func (_c *ProductService_Update_Call) Run(run func(n int64, stringToIfaceVal map[string]interface{})) *ProductService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProductService_Update_Call) Return(err error) *ProductService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProductService_Update_Call) RunAndReturn(run func(n int64, stringToIfaceVal map[string]interface{}) error) *ProductService_Update_Call {
	_c.Call.Return(run)
	return _c
}
